### ISSUE TITLE
AttributeError: 'LayerNorm' object has no attribute 'affine' 

### ISSUE THREAD

**Issue by xnfxnf7979** [Qiming-Huang/ssformer#2]
Hello, 
i tried 'python train.py configs/ssformer-L.yaml'.. (edit dataset path, pretrained_path, checkpoint_save_path, logger_path)
and there's an error

Traceback (most recent call last):
  File "train.py", line 56, in <module>
    macs, params = profile(model, inputs=(input, ))
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/thop/profile.py", line 212, in profile
    model(*inputs)
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ssformer/models/mit/mit_PLD_b4.py", line 456, in forward
    features = self.backbone(x)
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ssformer/models/mit/mit_PLD_b4.py", line 259, in forward
    x = self.forward_features(x)
  File "/ssformer/models/mit/mit_PLD_b4.py", line 225, in forward_features
    x, H, W = self.patch_embed1(x)
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ssformer/models/mit/mit_PLD_b4.py", line 161, in forward
    x = self.norm(x)
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1123, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/thop/vision/basic_hooks.py", line 67, in count_normalization
    if m.affine:
  File "/home/user/.conda/envs/tf_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'LayerNorm' object has no attribute 'affine'

What did I do wrong?

**Comment by xnfxnf7979** [comment]
Can you tell me the version of 'torch' and 'thop'?

**Comment by FengciYeyu** [comment]
'/mnt/DATA-1/DATA-2/Feilong/scformer/models/mit/mit_b2.pth'

**Comment by FengciYeyu** [comment]
'/mnt/DATA-1/DATA-2/Feilong/scformer/models/mit/mit_b2.pth'
这个预训练的权重可以发一下吗？

**Comment by xnfxnf7979** [comment]
https://drive.google.com/file/d/1kDTpN42mLP-GjljSe7XyXsodU6BIPWx3/view?usp=sharing

here's the pretrained weight

**Comment by FengciYeyu** [comment]
test.py     Error: RuntimeError: DataLoader worker (pid(s) 11012) exited unexpectedly
train.py   Error: AttributeError: 'LayerNorm' object has no attribute 'affine'
......

**Comment by FengciYeyu** [comment]
train.py     torch.nn.modules.module.ModuleAttributeError: 'LayerNorm' object has no attribute 'affine'
test.py      RuntimeError: DataLoader worker (pid(s) 15516, 7080) exited unexpectedly

**Comment by Qiming-Huang** [comment]
> Can you tell me the version of 'torch' and 'thop'?

I upload the requirements.txt, feel free to check the version of those packages.
